### ISSUE TITLE
Unhandled Rejection (TypeError): (0 , _react.useState) is not a function…

### ISSUE THREAD

**Issue by stahlmanDesign** [adamsoffer/react-hubspot#1]
Unhandled Rejection (TypeError): (0 , _react.useState) is not a function or its return value is not iterable

I get this error using your example code and my hubspot protalId and formId

`useState` was a new feature part of v16.7.0-alpha
v16.7.0 has been released and I am using it. Did `useState` change since you last updated your code or am I doing something wrong?

**Comment by adamsoffer** [comment]
@stahlmanDesign ah yes, this package requires the latest alpha version of react (16.7.0-alpha.2). `v16.7.0` [doesn't include support for hooks](https://reactjs.org/blog/2018/12/19/react-v-16-7.html). Try `npm install --save react@next` in your app.
